### PR TITLE
Fixed a crash

### LINKED ISSUE #85: Props destroyed whilst connected to an expanding hydraulic crash the game.
This is pretty easy to recreate. Ignite or shoot a wood box while it is connected to an expanding hydraulic and the game will crash. It has to be expanding, not contracting or holding still. Removing the prop apparently isn't the same as destruction either and does not crash.

### LINKED ISSUE #137: discord server? (+hard crash error)
anyway. 
when i spawn this dupe : https://steamcommunity.com/sharedfiles/filedetails/?id=113272705

and i shoot and destroy the elevator...
IT HARD CRASHED MY GAME
will this be fixed? when i played a map and a cable was attached to a door. when the door sparked. and im guessing the cable was detached, or destroyed. my game once again froze. and crashed. without any way to reverse it. crashed to desktop.

### PR DESCRIPTION
**Pull request by RaphaelIT7**
[#] Fixed a crash

Related issues:
fixes #137
fixes #85

### CODE REVIEW

**Comment by Joshua-Ashton** [comment]
Let's come back to this after 0.20, do you have a repro case?

**Comment by RaphaelIT7** [comment]
I'll can get one in a few hours

**Comment by YUCLing** [comment]
> Let's come back to this after 0.20, do you have a repro case?

Maybe check the related issues? It looks like it's simple to repro in GMod with an expanding hydraulic.

**Comment by RaphaelIT7** [comment]
Latest Build:

https://github.com/user-attachments/assets/11c861d7-ffd2-4bc7-ad82-c437e9eb188c

**Comment by RaphaelIT7** [comment]
I did a bit more testing, and it seems like `JoltPhysicsSpring::OnJoltPhysicsObjectDestroyed` will be called and then it breaks. 
If a prop is connected to the world, it will crash in `JoltPhysicsSpring::SetSpringLength` because the `m_pObjectStart` was deleted, but there is no null check so it'll try to use it.  
I'll try to test it future again tomorrow, but it seems like the crash in the video is a different one? 
(I don't remember it ever crashing in one of the `JoltPhysicsSpring` functions when I made the pr)

**Comment by Joshua-Ashton** [comment]
Is it not set up to have an OnDestroyedListener?

**Comment by RaphaelIT7** [comment]
It has and `OnJoltPhysicsObjectDestroyed` will be called to set `m_pObjectStart` to ``nullptr` but it's still used / the engine still calls SetSpringLength and in that function you don't check if it's null

**Comment by Joshua-Ashton** [comment]
I guess MR that NULL check? :-)

**Comment by RaphaelIT7** [comment]
So It seems like I found the cause, and it should now be fixed for all cases :D

I also reverted the original two commits, since it seems like they didn't really do anything. 
I wonder why they fixed it on the dupe months ago.

**Pull request merged**
