### PR TITLE
Fixed Level transition and Fixed Gmod crashing.

### LINKED ISSUE #60: [GMOD] Server crash
I'm using win32 and this occurs when i use changelevel <map> a minute or two later the server just crashes the auto restarts on its own
image_2022-09-01_134023206

### LINKED ISSUE #126: [BUG] F6 crashes G-Mod
Whenever I quicksave via F6, the game simply crashes. It freezes and it closes.
Nothing useful in logs, although I have an mdmp if it may be useful.

I am using the latest version of Volt (0.11) on the latest version of G-Mod (x86-64) and on Windows Home 21H1 (19044.2006) x64.

Steps to reproduce:
1.  Join any game and press F6
2. Crash

### LINKED ISSUE #139: Combine APCs crash the game when destroyed
Easy to reproduce if you play on some HL2 maps, or custom campaign maps that use APCs.

### LINKED ISSUE #155: Crash on levelchange
Game will crash when changing levels using level transitions when this is installed

### LINKED ISSUE #166: [GMod x64] Crashing on legacy HL2 saving/changelevels
Tested with **-noaddons** and **-noworkshop**

Saving using the legacy HL2 save file system crashes GMod with Volt physics.
This is significant for the HL2 campaign maps as they make use of **logic_autosave** which forces saves to be made.
**logic_autosave**'s _Save_ and _SaveDangerous_ inputs, and the **save** console command were observed to be affected.
The **trigger_changelevel** entities used often in the campaign maps also crash on attempt to change map.

_Extra note:_ In a quick test of loading save files made with normal VPhysics into Volt, GMod doesn't crash, but physics objects were frozen and physics ragdolls' models were crushed into **0, 0, 0,** the map origin.

Crash dumps of both methods just in-case:
[crashes.zip](https://github.com/Joshua-Ashton/VPhysics-Jolt/files/10497326/crashes.zip)

### PR DESCRIPTION
**Pull request by RaphaelIT7**
[#] Fixed a crash in Gmod related to ConVars (Thanks to Rubat who helped me find the approximate cause of the crash)

I don't exactly know why the removed delete statements crashed the game (HL2), but they did.

Related Issues:
fixes #166 
fixes #155 
fixes #60 

ToDo:
- [x] Fix Vehicles crashing the game when you sit in them and remove them ([Crashed somewhere here](https://github.com/nillerusr/source-engine/blob/master/game/server/physics.cpp#L1721))
- [x] Fix the mini-sourcesdk and remove the ConVar workaround
mini-source-sdk pr: https://github.com/Joshua-Ashton/mini-source-sdk/pull/3

### CODE REVIEW

**Comment by NathanX-S** [comment]
Is this repository being managed at all or should it be forked/handed off to a new maintainer..? @Joshua-Ashton

**Comment by Joshua-Ashton** [comment]
This MR does nothing. It just adds a bunch of ifdefs around code that was already compiled for Garry's Mod.

image

**Comment by RaphaelIT7** [comment]
Coming back to this, this looks more like a workaround instead of an actual fix, so I'm closing this for now. 
Maybe I'll come back to this later and try to fix it properly

**Comment by Joshua-Ashton** [comment]
It doesn't work around anything though. GAME_GMOD is always defined for... gmod.

**Comment by RaphaelIT7** [comment]
With workaround, I mean these delete changes.
Only deleting stuff in Gmod doesn't seem like a proper solution to solve the crashes that I had in HL2.
The PR to stop the ConVars from crashing should have solved #60 and #166 and these delete changes should solve #155, but I don't think that this is really the solution for it

**Pull request closed without merging**
